CREATE TABLE "stack-duel_problem" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_problem_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	CONSTRAINT "stack-duel_problem_slug_unique" UNIQUE("slug")
);
