CREATE TYPE "public"."stack_duel_decision_effect" AS ENUM('Allow', 'Deny');--> statement-breakpoint
CREATE TYPE "public"."stack_duel_problem_status" AS ENUM('Draft', 'Published', 'Archived');--> statement-breakpoint
CREATE TABLE "stack-duel_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actorUserId" integer,
	"actorUsername" varchar(64) NOT NULL,
	"action" varchar(128) NOT NULL,
	"targetType" varchar(64),
	"targetId" varchar(128),
	"detailsJson" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stack-duel_feature_flag_group_override" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_feature_flag_group_override_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"flagId" integer NOT NULL,
	"groupId" integer NOT NULL,
	"effect" "stack_duel_decision_effect" NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_feature_flag_group_override_flagId_groupId_unique" UNIQUE("flagId","groupId")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_feature_flag_user_override" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_feature_flag_user_override_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"flagId" integer NOT NULL,
	"userId" integer NOT NULL,
	"effect" "stack_duel_decision_effect" NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_feature_flag_user_override_flagId_userId_unique" UNIQUE("flagId","userId")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_feature_flag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_feature_flag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(128) NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"defaultEnabled" boolean DEFAULT false NOT NULL,
	"rolloutPercentage" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_feature_flag_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"permissions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_group_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_user_group" (
	"userId" integer NOT NULL,
	"groupId" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_user_group_userId_groupId_pk" PRIMARY KEY("userId","groupId")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkId" varchar(128) NOT NULL,
	"username" varchar(64) NOT NULL,
	"bio" text,
	"imageUrl" text,
	"isPrivate" boolean DEFAULT false NOT NULL,
	"usernameLastChangedAt" timestamp with time zone,
	"setupCompletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_user_clerkId_unique" UNIQUE("clerkId"),
	CONSTRAINT "stack-duel_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_language_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_language_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"languageId" integer NOT NULL,
	"version" varchar(32) NOT NULL,
	"judge0LanguageId" integer,
	CONSTRAINT "stack-duel_language_version_languageId_version_unique" UNIQUE("languageId","version")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_language" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_language_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(64) NOT NULL,
	CONSTRAINT "stack-duel_language_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_problem_public_test_case" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_problem_public_test_case_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"problemId" integer NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"inputs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"expectedOutputs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "stack-duel_problem_public_test_case_problemId_name_unique" UNIQUE("problemId","name")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_problem_reaction" (
	"problemId" integer NOT NULL,
	"userId" integer NOT NULL,
	"reactionTypeKey" varchar(32) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_problem_reaction_problemId_userId_pk" PRIMARY KEY("problemId","userId")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_problem_setup" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_problem_setup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"problemId" integer NOT NULL,
	"languageVersionId" integer NOT NULL,
	"functionName" varchar(128),
	"initialCode" text DEFAULT '' NOT NULL,
	"additionalFiles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT "stack-duel_problem_setup_problemId_languageVersionId_unique" UNIQUE("problemId","languageVersionId")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_problem" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_problem_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"question" text DEFAULT '' NOT NULL,
	"difficultyValue" integer DEFAULT 0 NOT NULL,
	"difficultyTier" varchar(32) DEFAULT 'Beginner' NOT NULL,
	"timeLimitMs" integer DEFAULT 2000 NOT NULL,
	"memoryLimitMb" integer DEFAULT 256 NOT NULL,
	"status" "stack_duel_problem_status" DEFAULT 'Draft' NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"authorUserId" integer,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_problem_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "stack-duel_reaction_type" (
	"key" varchar(32) PRIMARY KEY NOT NULL,
	"name" varchar(64) NOT NULL,
	"emoji" varchar(8)
);
--> statement-breakpoint
ALTER TABLE "stack-duel_audit_log" ADD CONSTRAINT "stack-duel_audit_log_actorUserId_stack-duel_user_id_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."stack-duel_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_feature_flag_group_override" ADD CONSTRAINT "stack-duel_feature_flag_group_override_flagId_stack-duel_feature_flag_id_fk" FOREIGN KEY ("flagId") REFERENCES "public"."stack-duel_feature_flag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_feature_flag_group_override" ADD CONSTRAINT "stack-duel_feature_flag_group_override_groupId_stack-duel_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."stack-duel_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_feature_flag_user_override" ADD CONSTRAINT "stack-duel_feature_flag_user_override_flagId_stack-duel_feature_flag_id_fk" FOREIGN KEY ("flagId") REFERENCES "public"."stack-duel_feature_flag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_feature_flag_user_override" ADD CONSTRAINT "stack-duel_feature_flag_user_override_userId_stack-duel_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."stack-duel_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_user_group" ADD CONSTRAINT "stack-duel_user_group_userId_stack-duel_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."stack-duel_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_user_group" ADD CONSTRAINT "stack-duel_user_group_groupId_stack-duel_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."stack-duel_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_language_version" ADD CONSTRAINT "stack-duel_language_version_languageId_stack-duel_language_id_fk" FOREIGN KEY ("languageId") REFERENCES "public"."stack-duel_language"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_public_test_case" ADD CONSTRAINT "stack-duel_problem_public_test_case_problemId_stack-duel_problem_id_fk" FOREIGN KEY ("problemId") REFERENCES "public"."stack-duel_problem"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_reaction" ADD CONSTRAINT "stack-duel_problem_reaction_problemId_stack-duel_problem_id_fk" FOREIGN KEY ("problemId") REFERENCES "public"."stack-duel_problem"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_reaction" ADD CONSTRAINT "stack-duel_problem_reaction_userId_stack-duel_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."stack-duel_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_reaction" ADD CONSTRAINT "stack-duel_problem_reaction_reactionTypeKey_stack-duel_reaction_type_key_fk" FOREIGN KEY ("reactionTypeKey") REFERENCES "public"."stack-duel_reaction_type"("key") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_setup" ADD CONSTRAINT "stack-duel_problem_setup_problemId_stack-duel_problem_id_fk" FOREIGN KEY ("problemId") REFERENCES "public"."stack-duel_problem"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem_setup" ADD CONSTRAINT "stack-duel_problem_setup_languageVersionId_stack-duel_language_version_id_fk" FOREIGN KEY ("languageVersionId") REFERENCES "public"."stack-duel_language_version"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stack-duel_problem" ADD CONSTRAINT "stack-duel_problem_authorUserId_stack-duel_user_id_fk" FOREIGN KEY ("authorUserId") REFERENCES "public"."stack-duel_user"("id") ON DELETE set null ON UPDATE no action;