CREATE TABLE "stack-duel_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stack-duel_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkId" varchar(128) NOT NULL,
	"username" varchar(64) NOT NULL,
	"bio" text,
	"imageUrl" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "stack-duel_user_clerkId_unique" UNIQUE("clerkId"),
	CONSTRAINT "stack-duel_user_username_unique" UNIQUE("username")
);
